### ISSUE TITLE
table.sql  缺少表和字段

### ISSUE THREAD

**Issue by zmmjsw** [incubator-kob/kob-parent#2]
缺少表  'kob.kob_project_user_incubator' 
缺少字段  表kob_task_waiting_incubator 的   batch_type，retry_type

**Comment by zhaoyuguang** [comment]
https://github.com/incubator-kob/kob-parent/wiki/%E6%95%B0%E6%8D%AE%E8%A1%A8%E5%88%9B%E5%BB%BA
